### ISSUE TITLE
Can't find the assistant's answers in the history

### ISSUE THREAD

**Issue by OSDkorben** [microsoft/sample-app-aoai-chatGPT#1093]
**Describe the bug**
Hello, 
I updated my prod with last commit "3a6c7b7", and since then, the assistant's response history is no longer being saved in the database. 
Do you have any idea?
![plop](https://github.com/user-attachments/assets/fdfbfff7-613d-465c-b6c2-2afec6f150a9)

**Comment by lathcf** [comment]
I noticed this yesterday also, but since no one was talking about it I thought it might have been some other change I had done. The issue is coming from the change at line 655 in Chat.tsx. It is causing history/update to never fire so it isn't saving the assistant response.

![image](https://github.com/user-attachments/assets/ca63b132-ce8b-4168-9e49-e17f627923a6)

**Comment by OlegDStassenko** [comment]
Oh ok, thank you for your response!
Do you think the patch will be able to be deployed to the main branch soon?
