### ISSUE TITLE
(#200) - Update index creation script to support vectors - Not create index

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#206]
I'm using the version made available last Friday (08/25) that contains the option to create an index using a vector. Following the described step-by-step, I cannot create the index because it always displays the following message:

Chunking directories...
Total files to process=2 out of total directory size=2
Multiprocessing with njobs=4
   0%| | 0/2 [00:00<?, ?it/s]SingletonFormRecognizerClient: Creating instance of Form recognizer per process
SingletonFormRecognizerClient: Skipping since credentials not provided. Assuming NO form recognizer extensions(like .pdf) in directory

SingletonFormRecognizerClient: Skipping since credentials not provided. Assuming NO form recognizer extensions(like .pdf) in directory
File (C:\project_documents\Documentation Master List.pdf) failed with 'object' object has no attribute 'begin_analyze_document

I also tried to create the index without using vector without informing the vector parameter, using the following command to create the index "az cognitiveservices account keys list --name "<form-rec-resource-name>" --resource-group "< resource-group-name>" displays the following message:

Preparing data for index: gptkbindex
Traceback (most recent call last):
   File "C:\projects\test\scripts\data_preparation.py", line 420, in <module>
     raise Exception("ERROR: Vector search is enabled in the config, but no embedding model endpoint and key were provided. Please provide these values or disable vector search.")
Exception: ERROR: Vector search is enabled in the config, but no embedding model endpoint and key were provided. Please provide these values or disable vector search.

In this case I am not using vector in the index and I believe it should be created without the vector option.

**Comment by sarah-widder** [comment]
Hi @edercarlima we recently merged some fixes in #207 - do you mind pulling main and giving it another try? For the no-vector option, make sure config.json does not set `vector_config_name` otherwise it will still try to add vectors.

**Comment by edercarlima** [comment]
Hi @sarah-widder 
I did the test without the vector_config_name parameter in the config.json file and I also couldn't create the index.

I'm going to download the version that contains fix 207 and test it.
Once the tests are finished, I'll let you know the result.

**Comment by malamirada** [comment]
I was facing the same error as @edercarlima but, as @sarah-widder says, now is solved. Thanks!!

**Comment by edercarlima** [comment]
Hi @sarah-widder 

I download the latest version from GitHub and managed to create the index without vectorization using the script. For this situation, in the config.json file I did not inform the parameter "vector_config_name": "default".

When trying to index with the vector option, include in the config.json file the parameter "vector_config_name": "default". and follow the step by step as described on github. When trying to create the index, it displays the following message:

Preparing data for index: gptkbindex02
Using existing search service gptkb-jyxxxxxxxxxx
Created search index gptkbindex02
Chunking directory...
Total files to process=4 out of total directory size=4
Multiprocessing with njobs=4
  0%|                                                                                                                         | 0/4 [00:00<?, ?it/s]SingletonFormRecognizerClient: Creating instance of Form recognizer per process
SingletonFormRecognizerClient: Skipping since credentials not provided. Assuming NO form recognizer extensions(like .pdf) in directory
File (C:\projetos_documentos\compliance\CO 0-00 - Lista Mestra da Documentação.pdf) failed with  'object' object has no attribute 'begin_analyze_document'
 25%|████████████████████████████▎                                                                                    | 1/4 [00:08<00:25,  8.39s/it]File (C:\projetos_documentos\compliance\CO 1-01 - Relação com Concorrentes e Política AntitrusteBS.pdf) failed with  'object' object has no attribute 
'begin_analyze_document'
File (C:\projetos_documentos\compliance\CO 1-02 - Relação com FornecedoresBS.pdf) failed with  'object' object has no attribute 'begin_analyze_document'
SingletonFormRecognizerClient: Creating instance of Form recognizer per process
SingletonFormRecognizerClient: Skipping since credentials not provided. Assuming NO form recognizer extensions(like .pdf) in directory
File (C:\projetos_documentos\compliance\CO 0-00 - Manual de Documentação do Sistema de ComplianceBS.pdf) failed with  'object' object has no attribute 'begin_analyze_document'
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:09<00:00,  2.26s/it]
Traceback (most recent call last):
  File "C:\projetos\sample-app-aoai-chatGPT-main\scripts\data_preparation.py", line 426, in <module>
    create_index(index_config, credential, form_recognizer_client, use_layout=args.form_rec_use_layout, njobs=args.njobs)
  File "C:\projetos\sample-app-aoai-chatGPT-main\scripts\data_preparation.py", line 369, in create_index
    raise Exception("No chunks found. Please check the data path and chunk size.")
Exception: No chunks found. Please check the data path and chunk size.


the data preparation script was assembled as follows:
python data_preparation.py --config config.json --embedding-model-endpoint https://gptkb-jyxxxxxxxxxx.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2023-06-01-preview --embedding-model-key 3b8888088d844c9b43488xxxxxxxxxx

Could you help me with this doubt?

**Comment by sarah-widder** [comment]
Hi @edercarlima from the error message, it looks like you have PDF documents in your data folder, but you haven't passed through a Document Intelligence (Form Recognizer) resource and key to crack the PDFs. Please create a resource and use it to crack the PDFs https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/overview?view=doc-intel-3.1.0

**Comment by sarah-widder** [comment]
Closing this issue.

**Comment by jbao8899** [comment]
I am running into similar issues with the latest version of this script. I can create an index without vectors, but not one with them. I did:

[
    {
        "data_path": "...",
        "location": "...",
        "subscription_id": "...",
        "resource_group": "...",
        "search_service_name": "...",
        "index_name": "...",
        "chunk_size": ...,
        "token_overlap": ...,
        "semantic_config_name": "default",
        "language": "en",
        "vector_config_name": "default"
    }
]

With everything being the same as the config file for the non-vector index, except for the index name and adding "vector_config_name": "default".

I used the command:

py data_preparation.py --config config_vector.json --embedding-model-endpoint "https://<azure openai resource name>.openai.azure.com/openai/deployments/<ada deployment name>/embeddings?api-version=2023-11-01" --embedding-model-key <the key for my Azure OpenAI service>

I get the error message:

`
Data preparation script started
Preparing data for index: <index name>
Using existing search service <search service name>
Created search index <search index name>
Chunking path <path>...
Total files to process=1 out of total directory size=1
Multiprocessing with njobs=4
  0%|                                                                                                                                      | 0/1 [00:00<?, ?it/s]SingletonFormRecognizerClient: Creating instance of Form recognizer per process
SingletonFormRecognizerClient: Skipping since credentials not provided. Assuming NO form recognizer extensions(like .pdf) in directory
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [04:00<00:00, 240.70s/it]
Traceback (most recent call last):
  File "<preceeding path>\sample-app-aoai-chatGPT\scripts\data_preparation.py", line 464, in <module>
    create_index(index_config, credential, form_recognizer_client, embedding_model_endpoint=args.embedding_model_endpoint, use_layout=args.form_rec_use_layout, njobs=args.njobs)
  File "C<preceeding path>\sample-app-aoai-chatGPT\scripts\data_preparation.py", line 404, in create_index
    raise Exception("No chunks found. Please check the data path and chunk size.")
Exception: No chunks found. Please check the data path and chunk size.
`

What is going on?

What deployment endpoint am I supposed to be using? I cannot see one specifically for the embedding deployment (and not the whole service) listed on the Azure portal or on Azure OpenAI studio. I tried both api-version=2023-06-01-preview and api-version=2023-11-01. Neither worked, and in both cases, an empty index using an old api version was used (2023-07-01-preview).

What am I supposed to do about the embedding key? I cannot find one specifically for the embedding deployment. I tried using the key for my Azure OpenAI service as a whole, but including and excluding it did not seem to make a difference. In fact, I could not see where it was used in the code (which I do not fully understand).

Why does this successfully chunk my file and create an index when I am not using vectors, but fail when I am trying to use them?

**Comment by Chriss-24** [comment]
I have exactly the same issue as @jbao8899. Have you manage the way to solve this?
