### ISSUE TITLE
Chats not working with history enabled 

### ISSUE THREAD

**Issue by spedditi** [microsoft/sample-app-aoai-chatGPT#246]
I am running into issues when chat history is enabled; application is not responding to any questions, I know that there is a api limit of 1000 token per min in my subscription. If i disable chat history application in working. 
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/26589865/a610e97c-5d99-4fa0-a027-5e865cee0511)

**Comment by sarah-widder** [comment]
Hi @spedditi, when using data, the model prompt ends up being quite long (as it includes sections of your documents, it can be around 6000 tokens) which may already be crossing your 1000 tokens per minute limit. When using chat history, there is also one additional call to the model for new conversations to generate a title for the conversation based on the user's first message. This is a short prompt/response but may contribute to your limit. If you want to skip the title generation call to save on tokens, you can modify this line in app.py: https://github.com/microsoft/sample-app-aoai-chatGPT/blob/80bd8c94f9e6f83c0702b108e2c41f4bf4025d30/app.py#L372C13-L372C61. For example, use the (first few words of) user's message verbatim as the title instead of generating one. Hope that helps.
