### ISSUE TITLE
Storing history and cleaning chat.

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#248]
I have the following problem. I downloaded it from github and deployed it.
After the deployment, I checked in the resource group that the CosmoDB structure was created.
I created the index and asked the questions and when I click to clear, it doesn't clear.
To enable cleaning and storage of history, do I need to perform some procedure or upload the json file that is in the infrastructure through the azure template?

**Comment by sarah-widder** [comment]
Hi @edercarlima - can you be a little more specific about the error you're facing, or perhaps provide a screenshot? Specifically, is the issue with creating chat history entries, the 'broom' button that clears the chat, or both.

If you deployed the resources with azd, there was a misconfiguration of the CosmosDB that caused failures. This was fixed in #250 if you want to try redeploying your resources, it may resolve some of the behavior you're seeing.

**Comment by edercarlima** [comment]
Evidence:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/138822712/d4e6c6f9-da1c-4328-954a-ccd20b770c69)

**Comment by edercarlima** [comment]
Hi @sarah-widder. 
I carried out the tests and managed to solve the problem. Now the icons are appearing, and I can include, update, delete and consult the chat history.

As a suggestion:
1 - there should be an option to disable chat history and allow conversations to be cleaned. In other words, having the previous chat option without recording history and clearing current conversations.
2 - When deplpying, create the CosmoDB variables in the application configuration. I had to create the new variables manually
3 - Parameterize the system message that sets the title of the message history, as it is now hardcoded in the code.

**Comment by sarah-widder** [comment]
Hi @edercarlima, 
For 1 - #252 should fix that issue. When chat history is disabled the broom button should work again as before.
For 2 and 3 - thanks for the suggestions! We will look into adding this support.

I'll close this issue for now.
