### ISSUE TITLE
The data preparation script failed to add vector embeddings

### ISSUE THREAD

**Issue by rongyu021** [microsoft/sample-app-aoai-chatGPT#254]
Ran python data_preparation.py --config config.json --embedding-model-endpoint "<embedding endpoint>" but it always fails. If I remove --embedding-model-endpoint, it would work fine. The exception contains this message "Principal does not have access to API/Operation" which indicates it can't successfully connect to the embedding model on AOAI.

**Comment by pamelafox** [comment]
The data_preparation script expects a key, --embedding-model-key:

https://github.com/microsoft/sample-app-aoai-chatGPT/blob/dd850ffdfbf183543594b5b8d14565e2ae8c9345/scripts/data_preparation.py#L402

Did you try passing that?

There's also a prepdocs.py script used by the azd deployment process which relies on roles, that but would only work if you used `azd up` to provision the resources and roles.

**Comment by sPaCeMoNk3yIam** [comment]
@pamelafox 
I think it's kind of connected, but it seems there is a bug where `AZURE_OPENAI_EMBEDDING_ENDPOINT` is not defined when using `azd up`.

The model is correctly automatically deployed and available at `https://<azure openai resource name>.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2023-06-01-preview` but the environment is missing and thus not correctly passed to the shell script https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/scripts/prepdocs.sh#L6
As I'm not using PowerShell, but having a look at the corresponding script, the arg is completely missing there.

Basically, because of this, `azd up` didn't work for me out of the box and I had to debug to find out the env is missing.

Lastly, maybe not directly connected, but when running `az ml job create --resource-group <workspace resource group> --workspace-name <workspace name> --file pipeline.yml` after following and adjusting the `pipeline.yml` for local data and creating the necessary services mentioned in https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/scripts/readme.md and configuring them in https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/scripts/config_multiple_url.json I run into a credential error. I asked a question about this first, as I don't know if it's my fault ar a bug, here: https://github.com/microsoft/sample-app-aoai-chatGPT/discussions/390

Thanks in advance for your support.

cc @sarah-widder
