### ISSUE TITLE
Productionizing the application for 1000 users

### ISSUE THREAD

**Issue by npsquared** [microsoft/sample-app-aoai-chatGPT#526]
Any tips or recommendations on productionizing this app for a 1000 users? 
I found this guide in the other repo: https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/productionizing.md

Anyone who was able to successfully put this in production, please comment. 

Thank you.

**Comment by log2** [comment]
Hello, I have the same aim for the app in my case, so I'm looking at not-ready-for-production pitfalls in order to remove them.

I think that some parts of the application should be looked upon carefully; for example, passing the `message_uuid`  of the assistant message being build using a global variable is fragile (see [here](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/app.py#L125) for the variable definition, [here](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/app.py#L618) for the assignment performed in a service, but used in the context of other services such as content streaming).

**Comment by sarah-widder** [comment]
Hi @npsquared @log2 #460 was merged yesterday and aims to prepare the app for production by refactoring to async. This would allow for many more simultaneous users. We are also looking into refactoring the global `message_uuid`. If you have additional feedback or suggestions please do let us know :)

**Comment by sarah-widder** [comment]
Update - #623 removed the global `message_uuid`

**Comment by npsquared** [comment]
Thanks for the amazing work, @sarah-widder!
I have incorporated the async refactor and the global message_uuid update to my fork. So far so good. 
I am looking to put this in production by the end of next week. I will start a discussion post at some point to summarize our experience putting this app in production. 

Any other thoughts, @log2 ?

**Comment by sgkalyans** [comment]
Hi, the cosmos DB returning 400 bad requests when application been accessed by many users at the same time but no issue when accessed by 1 or 2 users at the same time.   The error occurred in "create_message" method.  
![image](https://github.com/user-attachments/assets/06cef8b4-2d03-4b57-92ac-f16a8669ab60)
