### ISSUE TITLE
Logo and Branding - The app is showing Contoso logo and Branding instead of Azure

### ISSUE THREAD

**Issue by adaikalaraj** [microsoft/sample-app-aoai-chatGPT#553]
![contoso](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/10919589/688beb71-53d8-4e65-bb9e-ab56424aa01b)

**Comment by adaikalaraj** [comment]
> This is not an issue: Contoso is a fictional company used by Microsoft as an example company and domain. This rebranding has been made on purpose by the project team (see pull request here: #486), probably to help companies see that as a their own tool, not an "Azure resource".

When I deploy from OAI portal (https://oai.azure.com/portal). The app get deployed with the Contoso brand and logo. Is there any option to change it.

**Comment by nrobert** [comment]
See README section: https://github.com/microsoft/sample-app-aoai-chatGPT?tab=readme-ov-file#updating-the-default-chat-logo-and-headers

This section has not been updated with "Contoso" instead of "Azure" but it's the same logic, see the code here https://github.com/microsoft/sample-app-aoai-chatGPT/blob/33564a9a1bb55a1ace4e4472bcbd876fd98b7ce0/frontend/src/pages/chat/Chat.tsx#L606

If you want to update this display, you will then have to rebuild the frontend and host your own image because the app deployed through the Azure OpenAI portal creates a web app which configuration points to this current github repository

**Comment by aagirre92** [comment]
I would like to know how to change this once it's deployed to azure app service. I have connected via FTPS and modified the content of that file, restarted the app but I see no changes (probably because I am missing something). Any ideas? (I have deployed this via the Azure OpenAI "bring your own data")

**Comment by aagirre92** [comment]
Hence there is no way of changing the logo using (for instance) FTPS within the app service and modifying the content?

**Comment by nrobert** [comment]
No, there is already at least one issue related to that feature request: #522
