### ISSUE TITLE
Data Preparation failed with --form-rec-use-layout

### ISSUE THREAD

**Issue by shulkx** [microsoft/sample-app-aoai-chatGPT#69]
Hi there,
I have a bunch of pdfs to be embedded by using data_preparation.py.
It can be converted successfully with the default setting:
`python data_preparation.py --config config.json --njobs=4 --form-rec-resource <form-rec-resource-name> --form-rec-key <form-rec-key>`
Since, in my pdfs, I have lots of tales inside, in your doc, it is recommended to pass in the argument --form-rec-use-layout.
However, the console comes with different errors for different pdfs:
```
File (./output/xxxx1.pdf) failed with  'pageFooter'
  7%|▋         | 19/261 [00:39<04:16,  1.06s/it]File (./output/xxxx2.pdf) failed with  'pageHeader'
 12%|█▏        | 32/261 [01:01<07:04,  1.85s/it]File (./output/xxxx3.pdf) failed with  'pageNumber'
 18%|█▊        | 48/261 [01:27<06:04,  1.71s/it]File (./output/xxxx4.pdf) failed with  'pageFooter'
```
Can anyone help to explain why this happens? Thanks.

**Comment by satarupaguha11** [comment]
This was a bug and is fixed in this PR: https://github.com/microsoft/sample-app-aoai-chatGPT/pull/77/files which has now been merged to main. Please feel free to pull the latest changes and try again.

Shedding some light on the logic-
When the text is extracted from a PDF document, it loses a lot of the format information such as headings, subheadings etc. While that information is not required by search retrieval process, it is still useful in displaying the citations. The layout model in Form Recognizer lets us recover some of the format information. We specifically make use of the role types "title" and "subHeading" - we map these to html headers h1 and h2 so that we display them appropriately in the citations. We do not use the other role types such as "footer". The reason you encountered the error you did is- the pdf file had role types other the two we use for format restoration. We didn't handle them appropriately earlier, and fixed that in this PR. Hope this helps!
