### ISSUE TITLE
Using data source results in ignored system message

### ISSUE THREAD

**Issue by FergusKidd** [microsoft/sample-app-aoai-chatGPT#85]
The system message seems to be completely ignored as soon as a data input is given, meaning the persona of the bot goes back to default.

Simple system messages such as "you reply in only one word" work fine until a dataset is attached, at which point the default response goes back to 'Hello! I'm here to help you with any questions you may have. Please feel free to ask anything.' no matter what the system message.

**Comment by sarah-widder** [comment]
Hi @FergusKidd @gingergenius when using data the system message provides guidance to the model but it will not strictly adhere to every instruction. See more information in the documentation: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data#system-message

**Comment by zafissa** [comment]
I know this is closed but I have resolved this (looking at the Azure OpenAI payload). Add an additional parameter - roleInformation to the call going to the open AI service.

**Comment by AdamMiltonBarker** [comment]
This is crazy, we have large system prompts that define how our AI works, everything is ignored, even when using roleInformation. We have for instance specific instructions on the steps to take in a customer support case (Which our existing system handles perfectly), and it will completely ignore that and just keep responding with the same answer, the only way we can resolve this is to put all of our system prompts in the user prompt which is a security vulnerability. Two days integrating this feature to find out it is useless. 

We then thought to remove the call from the GPT call, extract the data before hand directly from AI Search (semantic) and pass it ourselves, and AI Search doesn't find the right documents if we do that, even if we ask it specific questions that are 100% in the document it just returns no answers and all of the documents in the index. 

This is the result of a conversation flow due to the system prompt being ignored, any follow up questions about something mentioned in the conversation it just continually repeats the same answer. You can see the reasoning we implemented is working, the AI comes to the correct understanding but then just repeats exactly what it said in the last message.

![image](https://github.com/user-attachments/assets/43eff76d-142a-40c9-a54e-5525dbd8889f)

**Comment by AdamMiltonBarker** [comment]
For anyone else that faces the issue above the only solution is not use BYOD, use the AI search as a separate service and use a combination of intent classification to track the context and AI search to retrieve the data, then send it to the LLM as normal in your system prompt. It is not possible to use BYOD for systems that rely on the system prompt as it just gets wiped out.

**Comment by Ashutosh2547** [comment]
I believe this has been implemented deliberatly to not to pass the System Message in prompt when using the external data source.
Just take a look at this [line](https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/app.py#L212), here you can se that if you set the data sources, you can't set the system message.
It is strange and I don't know the reason behind it.
When I removed the if block, system message was included in the messages array and the LLM responded the way I wanted it to respond.

**Comment by richardguinness** [comment]
FWIW I've found that system message is not ignored when using Azure Open AI On Your Data with OPENAI_API_VERSION="2024-06-01", whereas it is ignored when using "2023-08-01-preview".
