### ISSUE TITLE
"AZURE_SEARCH_QUERY_TYPE = vectorSimpleHybrid" not supported any more can causing the web app to not start

### ISSUE THREAD

**Issue by ThoSt81** [microsoft/sample-app-aoai-chatGPT#873]
**Describe the bug**
I've redeployed from Git today as I wanted to stay up to date via the Deployment Center (Sync).
This appeared to run through fine but the web app is no longer working and showing an "Application Error".

**Additional context**
It appears that the following setting is no longer supported/working:

AZURE_SEARCH_QUERY_TYPE = vectorSimpleHybrid

and I need to change this to:

AZURE_SEARCH_QUERY_TYPE = vector_simple_hybrid

The readme still lists vectorsimplehybrid as a valid option and this would need to be updated.

**Comment by abhahn** [comment]
Hi @ThoSt81 , thanks for reporting your issue.  I've just merged a change to allow camel case versions of the query types, since the Azure OpenAI Studio is still deploying apps with these values for now.  

I've just tested that using the "Sync" option from the Deployment Center in the Azure Portal should solve the issue.  I'm going to close this issue for now, but feel free to reopen if you continue to see a problem.
